# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Drivw E\BCS\Semester 3\Python\Project\Part 3\All Part 3\WelcomePanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.panel = QtWidgets.QWidget(MainWindow)
        self.panel.setObjectName("panel")
        
        self.pnlWmsg = QtWidgets.QWidget(self.panel)
        self.pnlWmsg.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.pnlWmsg.setStyleSheet("background-image:url(WLC1.jpg);")
        self.pnlWmsg.setObjectName("pnlWmsg")
        
        self.lblWlcUser = QtWidgets.QLabel(self.pnlWmsg)
        self.lblWlcUser.setGeometry(QtCore.QRect(160, 360, 691, 81))
        self.lblWlcUser.setStyleSheet("font: 75 35pt \"Arial\";\n"
"background:none;\n"
"color: rgb(255, 170, 0);")
        self.lblWlcUser.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWlcUser.setObjectName("lblWlcUser")
        MainWindow.setCentralWidget(self.panel)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblWlcUser.setText(_translate("MainWindow", "Baseer Ahmadzai"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
